apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.monitoring.svc.cluster.local:9093

    rule_files:
      - /etc/prometheus/rules/*.yaml

    scrape_configs:
      - job_name: "fastapi"
        metrics_path: /metrics
        static_configs:
          - targets:
              - app.devops-task.svc.cluster.local:8000
